import { councilSeo, councilBreadcrumb } from './council-seo.mjs';
import { council,councilLocales,localizedCouncil,councilPath,format,esc,clientConfig } from './council-i18n.mjs';
export { councilMethods } from './council-i18n.mjs';
export function renderMethodCard(method,{header,footer,locale='zh-CN'}) {
 const {ui:t,advisors}=localizedCouncil(locale);
 const advisor=advisors.find(a=>a.id===method.person);
 if(!advisor)throw new Error(`Unknown advisor: ${method.person}`);
 const index=advisor.questions.findIndex(q=>q.method===method.id);
 if(index<0)throw new Error(`Unreferenced method: ${method.id}`);
 const path=councilPath(locale,method.id),url=`https://luffyliu.com${path}`,back=`${councilPath(locale)}#advisor-${advisor.id}`;
 const identity=`<span class="method-person"><img src="/assets/council/${advisor.id}.png" width="44" height="44" alt="${esc(advisor.name)} · ${esc(t.illustration)}"><span><strong>${esc(advisor.name)}</strong><small>${advisor.name===advisor.english?'':esc(advisor.english)+' · '}${esc(t.perspective)}</small></span></span>`;
 const list=(label,items)=>`<section class="method-block"><h3>${esc(label)}</h3><ul>${items.map(item=>`<li>${esc(item)}</li>`).join('')}</ul></section>`;
 return `<!doctype html><html lang="${locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">${councilSeo({title:format(t.cardTitle,{title:method.title,name:advisor.name}),description:format(t.cardDescription,{title:method.title,name:advisor.name,summary:method.summary}),path,locale,id:method.id,graph:[
 {'@type':'WebPage','@id':url+'#webpage',url,name:method.title,description:method.summary,inLanguage:locale,isPartOf:{'@id':`https://luffyliu.com${councilPath(locale)}#webpage`},mainEntity:{'@id':url+'#method'}},
 {'@type':'CreativeWork','@id':url+'#method',name:method.title,identifier:method.id,abstract:method.summary,inLanguage:locale,isBasedOn:`${council.source}/blob/${council.sourceCommit}/product-advisory-council/references/methods.json`,isPartOf:{'@id':'https://luffyliu.com/product-advisory-council/#skill'}},
 councilBreadcrumb([[t.home,`${councilLocales[locale].prefix}/`],[t.name,councilPath(locale)],[method.title,path]])
]})}<meta name="theme-color" content="#f7f5ef"><link rel="icon" href="/favicon-32x32.png"><link rel="stylesheet" href="/assets/css/site.css?v=20260831-3"><link rel="stylesheet" href="/assets/css/council.css?v=2"><link rel="stylesheet" href="/assets/css/council-cards.css?v=2"></head><body class="council-page method-page"><a class="skip-link" href="#main">${esc(t.cardSkip)}</a>${header}<main id="main" class="method-shell" data-pagefind-body><nav class="method-breadcrumb" aria-label="${esc(t.breadcrumb)}"><a href="${back}">← ${esc(format(t.backTo,{name:advisor.name}))}</a><span>METHOD CARD / ${esc(method.id)}</span></nav><p class="method-eyebrow">${esc(t.cardEyebrow)}</p>
<article class="method-card" id="method-card"><div class="method-flipper"><div class="method-face method-front" id="method-front"><header>${identity}<span class="method-number">${esc(method.id)}</span></header><div class="method-title"><p>PRODUCT ADVISORY COUNCIL</p><h1>${esc(method.title)}</h1><span class="method-rule"></span><p class="method-teaser">${esc(method.summary)}</p></div><footer><span>${esc(t.cardLabel)}</span><span class="flip-hint" hidden>${esc(t.flipFront)} ↻</span></footer></div>
<div class="method-face method-back" id="method-back"><header>${identity}<span class="method-number">${esc(method.id)}</span></header><div class="method-content"><p class="method-side-label">${esc(t.methodSide)}</p><h2>${esc(method.title)}</h2><p class="method-summary">${esc(method.summary)}</p>${list(t.when,method.conditions)}${list(t.ask,method.questions)}${list(t.act,method.actions)}${list(t.boundaries,method.boundaries)}</div><footer><span>${esc(t.methodNote)}</span><span class="flip-hint" hidden>${esc(t.flipBack)} ↻</span></footer></div></div></article>
<p id="flip-status" class="method-status" role="status" aria-live="polite"></p><nav class="method-pagination" aria-label="${esc(t.browseCards)}">${index>0?`<a href="${councilPath(locale,advisor.questions[index-1].method)}">← ${esc(t.previous)}</a>`:`<span>${esc(t.first)}</span>`}<span>${String(index+1).padStart(2,'0')} / 04</span>${index<3?`<a href="${councilPath(locale,advisor.questions[index+1].method)}">${esc(t.next)} →</a>`:`<span>${esc(t.last)}</span>`}</nav><p class="method-attribution">${esc(t.attribution)}<br><a href="${council.source}/blob/${council.sourceCommit}/product-advisory-council/references/methods.json" target="_blank" rel="noreferrer">${esc(t.source)} ↗</a></p></main>${footer}${clientConfig(t)}<script type="module" src="/assets/js/council-cards.js?v=2"></script></body></html>\n`;
}
