import { councilSeo, councilBreadcrumb } from './council-seo.mjs';
import { council, councilLocales, localizedCouncil, councilPath, format, esc, clientConfig, installPrompt } from './council-i18n.mjs';
export { council } from './council-i18n.mjs';
const repo=council.source;
const img=(a,size=88,ui=localizedCouncil('zh-CN').ui)=>`<img src="/assets/council/${a.id}.png" width="${size}" height="${size}" alt="${esc(a.name)} · ${esc(ui.illustration)}">`;
const homeCopy = {
 'zh-CN':['产品顾问团','把一个产品问题，交给不同的思考方式。14 位产品与 AI 顾问视角，帮你拆解假设、保留分歧，把建议变成可以验证的下一步。','认识顾问团','公开仓库'],
 'zh-TW':['產品顧問團','把一個產品問題，交給不同的思考方式。14 位產品與 AI 顧問視角，幫你拆解假設、保留分歧，把建議變成可以驗證的下一步。','認識顧問團','公開儲存庫'],
 en:['Product Advisory Council','Explore a product decision through 14 product and AI perspectives. Challenge assumptions, preserve disagreement, and turn advice into a testable next step.','Meet the council','Public repository'],
 ja:['プロダクト顧問団','14のプロダクト・AIの視点から、仮説と選択肢を検討。意見の違いを残し、検証できる次の一歩へつなげます。','顧問団を見る','公開リポジトリ'],
 ko:['제품 자문단','14가지 제품·AI 관점으로 가정과 선택지를 검토합니다. 서로 다른 의견을 살리고 검증 가능한 다음 행동으로 연결합니다.','자문단 보기','공개 저장소'],
 es:['Consejo de producto','Explora tus decisiones desde 14 perspectivas de producto e IA. Contrasta supuestos, conserva los desacuerdos y define un siguiente paso que puedas comprobar.','Conoce el consejo','Repositorio público']
};
export function councilHomeCard(locale='zh-CN') {
 const [title,desc,cta,source]=homeCopy[locale];
 const {ui,advisors}=localizedCouncil(locale);
 return `<article class="work-row council-home"><div class="work-row-number" aria-hidden="true">02</div><div class="work-row-copy"><div class="product-lockup"><img src="/assets/council/council.png" width="58" height="58" alt=""><div><h3>${title}</h3><p>Product Advisory Council · AI Skill</p></div></div><p>${desc}</p><div class="work-meta"><span>14 ${esc(ui.perspectives)}</span><span>${council.methodCount} ${esc(ui.methods)}</span><span>GitHub</span></div><div class="project-links"><a href="${councilPath(locale)}" hreflang="${locale}">${cta} ↗</a><a href="${repo}" target="_blank" rel="noreferrer">${source} ↗</a></div></div><a class="council-home-wall" href="${councilPath(locale)}" aria-label="${cta}"><span class="council-home-portraits">${advisors.map(a=>img(a,64,ui)).join('')}</span><span class="council-home-caption">ONE QUESTION. DIFFERENT PERSPECTIVES. ↗</span></a></article>`;
}
export function renderCouncil({header,footer,locale='zh-CN'}) {
 const {ui:t,advisors}=localizedCouncil(locale);
 const path=councilPath(locale),url=`https://luffyliu.com${path}`;
 const guide=['zh-CN','zh-TW'].includes(locale)?`${repo}#安装一次即可`:`${repo}/blob/main/README.en.md#manual-installation`;
 return `<!doctype html><html lang="${locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">${councilSeo({title:t.seoTitle,description:t.seoDescription,path,locale,graph:[
 {'@type':'WebPage','@id':url+'#webpage',url,name:t.name,description:t.seoDescription,inLanguage:locale,isPartOf:{'@id':'https://luffyliu.com/#website'},mainEntity:{'@id':'https://luffyliu.com/product-advisory-council/#skill'},image:`https://luffyliu.com/assets/council/social-preview-${locale}.png`},
 {'@type':'SoftwareSourceCode','@id':'https://luffyliu.com/product-advisory-council/#skill',name:'Product Advisory Council',alternateName:t.name,description:t.seoDescription,codeRepository:repo,version:council.version,url:'https://luffyliu.com/product-advisory-council/',author:{'@type':'Person',name:'Luffy Liu',url:'https://luffyliu.com/'},runtimePlatform:t.runtime,inLanguage:'zh-CN'},
 councilBreadcrumb([[t.home,`${councilLocales[locale].prefix}/`],[t.name,path]])
]})}<meta name="theme-color" content="#f7f5ef"><link rel="icon" href="/favicon-32x32.png"><link rel="stylesheet" href="/assets/css/site.css?v=20260831-3"><link rel="stylesheet" href="/assets/css/council.css?v=2"></head><body class="council-page"><a class="skip-link" href="#main">${esc(t.skip)}</a>${header}<main id="main" class="council-shell" data-pagefind-body>
<nav class="council-crumb" aria-label="${esc(t.breadcrumb)}"><a href="${councilLocales[locale].prefix}/#work">${esc(t.allWork)}</a><span>/</span><span>${esc(t.name)}</span></nav>
<section class="council-hero"><div><p class="council-kicker"><span></span> PRODUCT ADVISORY COUNCIL <i>VOL. 01</i></p><h1>${esc(t.heroLead)}<br>${esc(t.heroBefore)}<em>14</em>${esc(t.heroAfter)}</h1><p class="council-lede">${esc(t.ledeOne)}<br>${esc(t.ledeTwo)}</p><div class="council-actions"><a class="council-primary" href="#meet">${esc(t.choose)} <span>↓</span></a><a href="${repo}" target="_blank" rel="noreferrer">${esc(t.github)} ↗</a></div></div><aside class="council-margin"><span class="council-mark">↗</span><p>${esc(t.marginOne)}<br>${esc(t.marginTwo)}</p><dl><div><dt>${esc(t.perspectives)}</dt><dd>14</dd></div><div><dt>${esc(t.methods)}</dt><dd>${council.methodCount}</dd></div><div><dt>${esc(t.package)}</dt><dd>01</dd></div></dl></aside></section>
<section id="meet" class="council-meet" aria-labelledby="meet-heading"><div class="council-section-head"><div><span class="council-kicker">01 / MEET YOUR COUNCIL</span><h2 id="meet-heading">${esc(t.meetTitle)}</h2></div><p>${esc(t.meetHint)}</p></div><p class="council-disclosure">${esc(t.disclosure)}</p>
<div class="council-room"><div class="council-wall" aria-label="${esc(t.selectAdvisor)}">${advisors.map((a,i)=>`<a class="advisor" href="#advisor-${a.id}" data-advisor="${a.id}" aria-controls="advisor-${a.id}"><span class="advisor-portrait">${img(a,88,t)}<span class="advisor-index">${String(i+1).padStart(2,'0')}</span></span><strong>${esc(a.name)}</strong><small>${esc(a.name===a.english?a.focus.split(' · ')[0]:a.english)}</small></a>`).join('')}<button type="button" class="council-empty-seat" id="copy-install" title="${esc(t.sendAgent)}: ${esc(t.agentNames)}" hidden><span aria-hidden="true">⧉</span><span class="install-label"><strong>${esc(t.copyInstall)}</strong><small>${esc(t.sendAgent)}</small><small>${esc(t.agentNames)}</small></span></button><noscript><a class="council-empty-seat" href="${guide}">${esc(t.getTeam)} ↗</a></noscript><div class="install-copy-feedback" hidden><p id="install-copy-status" role="status" aria-live="polite"></p><label for="install-command" hidden>${esc(t.manualCopy)}</label><textarea id="install-command" readonly hidden rows="8">${esc(installPrompt(t))}</textarea></div></div>
<div class="council-conversations"><p class="sr-only" id="advisor-status" role="status" aria-live="polite"></p><noscript><p>${esc(t.noScript)}</p></noscript>${advisors.map(a=>`<article class="advisor-panel" id="advisor-${a.id}" aria-labelledby="name-${a.id}" tabindex="-1"><header class="advisor-heading">${img(a,62,t)}<div><p>THE ${esc(a.english.toUpperCase())} PERSPECTIVE</p><h3 id="name-${a.id}">${esc(a.name)}<span>${esc(t.perspective)}</span></h3><small>${esc(a.focus)}</small></div></header><div class="advisor-questions">${a.questions.map((q,i)=>`<details name="questions-${a.id}"${i===0?' open':''}><summary><span>${String(i+1).padStart(2,'0')}</span><strong>${esc(q.question)}</strong><b aria-hidden="true">＋</b></summary><div class="advisor-answer"><p>${esc(q.answer)}</p><a class="method-link" href="${councilPath(locale,q.method)}">${esc(t.methodLink)} · ${esc(q.method)} ${esc(q.methodTitle)} ↗</a></div></details>`).join('')}</div><p class="advisor-footnote">${esc(t.exampleNote)}</p></article>`).join('')}</div></div></section>
<section class="council-how" aria-labelledby="how-heading"><div class="council-section-head"><div><span class="council-kicker">02 / FROM PERSPECTIVE TO ACTION</span><h2 id="how-heading">${esc(t.howTitle)}</h2></div><p>${esc(t.howHint)}</p></div><div class="council-steps">${[1,2,3].map(i=>`<article><span>0${i} — ${esc(t[`step${i}Label`])}</span><h3>${esc(t[`step${i}Title`])}</h3><p>${esc(t[`step${i}Body`])}</p></article>`).join('')}</div></section>
<section class="council-install" id="install" aria-labelledby="install-heading"><div><p class="council-kicker">03 / TAKE IT WITH YOU</p><h2 id="install-heading">${esc(t.installHeading1)}<br>${esc(t.installHeading2)}</h2><p>${esc(t.installDescription1)}<br>${esc(t.installDescription2)}</p><div class="council-actions"><a class="council-primary" href="${repo}/releases/latest" target="_blank" rel="noreferrer">${esc(t.download)} <span>↗</span></a><a href="${guide}" target="_blank" rel="noreferrer">${esc(t.instructions)} ↗</a></div><small>${esc(t.packageNote)}</small></div><div class="council-prompt"><div><span>${esc(t.tryAsking)}</span><button id="copy-prompt" type="button" hidden>${esc(t.copyQuestion)} ↗</button></div><p id="example-prompt">${esc(t.examplePrompt)}</p><p class="prompt-tip">${esc(t.promptTip)}</p><span id="copy-status" role="status" aria-live="polite"></span></div></section>
<p class="council-colophon">${esc(format(t.colophon,{version:council.version}))}<a href="${repo}/tree/${council.sourceCommit}" target="_blank" rel="noreferrer">${esc(t.contentVersion)} ↗</a></p></main>${footer}${clientConfig(t)}<script type="module" src="/assets/js/council.js?v=2"></script></body></html>\n`;
}
