import { councilSeo, councilBreadcrumb } from "./council-seo.mjs";
import { promises as fs } from 'node:fs';
import { council } from './council.mjs';
const esc = (value) => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
export const councilMethods = JSON.parse(await fs.readFile(new URL('../../content/products/council-methods.json', import.meta.url), 'utf8'));
export function renderMethodCard(method, { header, footer }) {
  const advisor = council.advisors.find(a => a.id === method.person);
  if (!advisor) throw new Error(`Unknown advisor: ${method.person}`);
  const questionIndex = advisor.questions.findIndex(q => q.method === method.id);
  if (questionIndex < 0) throw new Error(`Unreferenced method: ${method.id}`);
  const route = id => `/product-advisory-council/cards/${id.toLowerCase()}/`;
  const back = `/product-advisory-council/#advisor-${advisor.id}`;
  const identity = `<span class="method-person"><img src="/assets/council/${advisor.id}.png" width="44" height="44" alt="${esc(advisor.name)}示意头像"><span><strong>${esc(advisor.name)}</strong><small>${esc(advisor.english)} · 分析视角</small></span></span>`;
  const list = (label, items) => `<section class="method-block"><h3>${label}</h3><ul>${items.map(item => `<li>${esc(item)}</li>`).join('')}</ul></section>`;
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">${councilSeo({ title: `${method.title} · ${advisor.name}方法卡 | 产品顾问团`, description: `${advisor.name}分析视角的「${method.title}」方法卡：${method.summary} 查看适用条件、思考问题、行动建议与方法边界。`, path: route(method.id), graph: [
 { '@type':'WebPage', '@id':`https://luffyliu.com${route(method.id)}#webpage`, url:`https://luffyliu.com${route(method.id)}`, name:method.title, description:method.summary, inLanguage:'zh-CN', isPartOf:{'@id':'https://luffyliu.com/product-advisory-council/#webpage'}, mainEntity:{'@id':`https://luffyliu.com${route(method.id)}#method`} },
 { '@type':'CreativeWork', '@id':`https://luffyliu.com${route(method.id)}#method`, name:method.title, identifier:method.id, abstract:method.summary, inLanguage:'zh-CN', isBasedOn:`${council.source}/blob/${council.sourceCommit}/product-advisory-council/references/methods.json`, isPartOf:{'@id':'https://luffyliu.com/product-advisory-council/#skill'} },
 councilBreadcrumb([['首页','/'],['产品顾问团','/product-advisory-council/'],[method.title,route(method.id)]])
] })}<meta name="theme-color" content="#f7f5ef"><link rel="icon" href="/favicon-32x32.png"><link rel="stylesheet" href="/assets/css/site.css?v=20260831-3"><link rel="stylesheet" href="/assets/css/council.css?v=1"><link rel="stylesheet" href="/assets/css/council-cards.css?v=1"></head><body class="council-page method-page"><a class="skip-link" href="#main">跳到方法卡</a>${header}<main id="main" class="method-shell" data-pagefind-body><nav class="method-breadcrumb" aria-label="面包屑"><a href="${back}">← 返回${esc(advisor.name)}的问答</a><span>METHOD CARD / ${esc(method.id)}</span></nav><p class="method-eyebrow">把一个方法，放进口袋。</p>
<article class="method-card" id="method-card"><div class="method-flipper"><div class="method-face method-front" id="method-front"><header>${identity}<span class="method-number">${esc(method.id)}</span></header><div class="method-title"><p>PRODUCT ADVISORY COUNCIL</p><h1>${esc(method.title)}</h1><span class="method-rule"></span><p class="method-teaser">${esc(method.summary)}</p></div><footer><span>产品顾问团 · 决策方法卡</span><span class="flip-hint" hidden>点击卡片，翻面阅读 ↻</span></footer></div>
<div class="method-face method-back" id="method-back"><header>${identity}<span class="method-number">${esc(method.id)}</span></header><div class="method-content"><p class="method-side-label">THE METHOD / 方法背面</p><h2>${esc(method.title)}</h2><p class="method-summary">${esc(method.summary)}</p>${list('什么时候用',method.conditions)}${list('先问自己',method.questions)}${list('可以怎么做',method.actions)}${list('别忽略这些边界',method.boundaries)}</div><footer><span>方法摘要 · 非本人原话</span><span class="flip-hint" hidden>点击卡片，回到正面 ↻</span></footer></div></div></article>
<p id="flip-status" class="method-status" role="status" aria-live="polite"></p><nav class="method-pagination" aria-label="浏览这位顾问的方法卡">${questionIndex>0?`<a href="${route(advisor.questions[questionIndex-1].method)}">← 上一张</a>`:'<span>第一张</span>'}<span>${String(questionIndex+1).padStart(2,'0')} / 04</span>${questionIndex<3?`<a href="${route(advisor.questions[questionIndex+1].method)}">下一张 →</a>`:'<span>最后一张</span>'}</nav><p class="method-attribution">依据公开技能包整理的分析方法，不是本人回答或背书。<br><a href="${council.source}/blob/${council.sourceCommit}/product-advisory-council/references/methods.json" target="_blank" rel="noreferrer">查看公开方法来源 ↗</a></p></main>${footer}<script type="module" src="/assets/js/council-cards.js"></script></body></html>\n`;
}
