import { councilSeo, councilBreadcrumb } from "./council-seo.mjs";
import { promises as fs } from 'node:fs';
const esc = (s) => String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export const council = JSON.parse(await fs.readFile(new URL('../../content/products/council.json', import.meta.url), 'utf8'));
const repo = council.source;
const img = (a, size=88) => `<img src="/assets/council/${a.id}.png" width="${size}" height="${size}" alt="${esc(a.name)}示意头像">`;
const homeCopy = {
 'zh-CN':['产品顾问团','把一个产品问题，交给不同的思考方式。14 位产品与 AI 顾问视角，帮你拆解假设、保留分歧，把建议变成可以验证的下一步。','认识顾问团','公开仓库'],
 'zh-TW':['產品顧問團','把一個產品問題，交給不同的思考方式。14 位產品與 AI 顧問視角，幫你拆解假設、保留分歧，把建議變成可以驗證的下一步。','認識顧問團（簡體中文）','公開儲存庫'],
 en:['Product Advisory Council','Explore a product decision through 14 product and AI perspectives. Challenge assumptions, preserve disagreement, and turn advice into a testable next step.','Meet the council (Chinese)','Public repository'],
 ja:['プロダクト顧問団','14のプロダクト・AIの視点から、仮説と選択肢を検討。意見の違いを残し、検証できる次の一歩へつなげます。','顧問団を見る（中国語）','公開リポジトリ'],
 ko:['제품 자문단','14가지 제품·AI 관점으로 가정과 선택지를 검토합니다. 서로 다른 의견을 살리고 검증 가능한 다음 행동으로 연결합니다.','자문단 보기 (중국어)','공개 저장소'],
 es:['Consejo de producto','Explora tus decisiones desde 14 perspectivas de producto e IA. Contrasta supuestos, conserva los desacuerdos y define un siguiente paso que puedas comprobar.','Conoce el consejo (chino)','Repositorio público']
};
export function councilHomeCard(locale='zh-CN') {
 const [title,desc,cta,source]=homeCopy[locale];
 return `<article class="work-row council-home"><div class="work-row-number" aria-hidden="true">02</div><div class="work-row-copy"><div class="product-lockup"><img src="/assets/council/council.png" width="58" height="58" alt=""><div><h3>${title}</h3><p>Product Advisory Council · AI Skill</p></div></div><p>${desc}</p><div class="work-meta"><span>14 perspectives</span><span>${council.methodCount} methods</span><span>GitHub</span></div><div class="project-links"><a href="/product-advisory-council/" hreflang="zh-CN">${cta} ↗</a><a href="${repo}" target="_blank" rel="noreferrer">${source} ↗</a></div></div><a class="council-home-wall" href="/product-advisory-council/" aria-label="${cta}"><span class="council-home-portraits">${council.advisors.map(a=>img(a,64)).join('')}</span><span class="council-home-caption">ONE QUESTION. DIFFERENT PERSPECTIVES. ↗</span></a></article>`;
}
export function renderCouncil({header,footer}) {
 const url='https://luffyliu.com/product-advisory-council/';
 return `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">${councilSeo({ title: '产品顾问团 AI Skill：14 个专家视角与决策方法卡 | Luffy Liu', description: '产品顾问团是一套产品与 AI 决策 Skill：14 个分析视角、148 张方法卡。点击头像探索 56 组示例问答，翻转方法卡查看行动建议，并复制安装指令交给你的 Agent。', path: '/product-advisory-council/', graph: [
 { '@type':'WebPage', '@id':url+'#webpage', url, name:'产品顾问团 · Product Advisory Council', description:'14 个产品与 AI 分析视角、148 张决策方法卡，以及 56 组示例问答。', inLanguage:'zh-CN', isPartOf:{'@id':'https://luffyliu.com/#website'}, mainEntity:{'@id':url+'#skill'}, image:'https://luffyliu.com/assets/council/social-preview.png' },
 { '@type':'SoftwareSourceCode', '@id':url+'#skill', name:'Product Advisory Council', alternateName:'产品顾问团', description:'按问题选择产品与 AI 分析视角的技能包，包含方法卡及本地群聊辅助脚本。', codeRepository:repo, version:council.version, url, author:{'@type':'Person', name:'Luffy Liu', url:'https://luffyliu.com/'}, runtimePlatform:'支持 Skills 的 AI 客户端；辅助脚本需要 Python 3.9+', inLanguage:'zh-CN' },
 councilBreadcrumb([['首页','/'],['产品顾问团','/product-advisory-council/']])
] })}<meta name="theme-color" content="#f7f5ef"><link rel="icon" href="/favicon-32x32.png"><link rel="stylesheet" href="/assets/css/site.css?v=20260831-3"><link rel="stylesheet" href="/assets/css/council.css?v=1"></head>
<body class="council-page"><a class="skip-link" href="#main">跳到正文</a>${header}<main id="main" class="council-shell" data-pagefind-body>
<nav class="council-crumb" aria-label="面包屑"><a href="/#work">所有作品</a><span>/</span><span>产品顾问团</span></nav>
<section class="council-hero"><div><p class="council-kicker"><span></span> PRODUCT ADVISORY COUNCIL <i>VOL. 01</i></p><h1>一个产品问题，<br>换 <em>14</em> 个角度想。</h1><p class="council-lede">产品顾问团，一套帮你思考产品决策的 AI Skill。<br>做什么、为谁做、值不值得做？让不同视角一起拆解。</p><div class="council-actions"><a class="council-primary" href="#meet">选一位，聊聊看 <span>↓</span></a><a href="${repo}" target="_blank" rel="noreferrer">在 GitHub 查看 ↗</a></div></div><aside class="council-margin"><span class="council-mark">↗</span><p>好的讨论，<br>不止一种答案。</p><dl><div><dt>顾问视角</dt><dd>14</dd></div><div><dt>决策方法卡</dt><dd>${council.methodCount}</dd></div><div><dt>完整技能包</dt><dd>01</dd></div></dl></aside></section>
<section id="meet" class="council-meet" aria-labelledby="meet-heading"><div class="council-section-head"><div><span class="council-kicker">01 / MEET YOUR COUNCIL</span><h2 id="meet-heading">这个问题，你想先问谁？</h2></div><p>点击头像 · 每位 4 组问答</p></div>
<p class="council-disclosure">以下为基于公开方法卡编写的 AI 分析示例，不是本人回答或背书。头像为示意插画。</p>
<div class="council-room"><div class="council-wall" aria-label="选择顾问">${council.advisors.map((a,i)=>`<a class="advisor" href="#advisor-${a.id}" data-advisor="${a.id}" aria-controls="advisor-${a.id}"><span class="advisor-portrait">${img(a)}<span class="advisor-index">${String(i+1).padStart(2,'0')}</span></span><strong>${esc(a.name)}</strong><small>${esc(a.english)}</small></a>`).join('')}<button type="button" class="council-empty-seat" id="copy-install" title="复制后发送给你的 Agent：Claude / Codex / Cursor / Workbuddy 等" hidden><span aria-hidden="true">⧉</span><span class="install-label"><strong>复制 AI 安装指令</strong><small>复制后发送给你的 Agent</small><small>Claude / Codex / Cursor / Workbuddy 等</small></span></button><noscript><a class="council-empty-seat" href="${repo}#安装一次即可">获取你的专家顾问团队 ↗</a></noscript><div class="install-copy-feedback" hidden><p id="install-copy-status" role="status" aria-live="polite"></p><label for="install-command" hidden>手动复制安装指令</label><textarea id="install-command" readonly hidden rows="8">请帮我安装「产品顾问团」Skill，让我可以在当前 Agent 中使用这套专家顾问团队。

公开仓库：https://github.com/CarGod/product-advisory-council

请先阅读仓库 README 和安装说明，识别你当前所在的客户端及其支持的技能安装方式，再完成安装。保留完整的 product-advisory-council 技能文件夹，不要只复制 SKILL.md；如果已有旧版本，请先备份再更新。

安装后检查技能文件是否完整、当前客户端是否能识别，并告诉我如何开始使用，以及是否需要新开会话。如果当前环境无法直接安装，请明确说明原因，并给出适合当前客户端的最少手动步骤，不要声称已经安装成功。</textarea></div></div>
<div class="council-conversations"><p class="sr-only" id="advisor-status" role="status" aria-live="polite"></p><noscript><p>以下展示全部顾问问答；点击头像可跳转到对应顾问。</p></noscript>${council.advisors.map(a=>`<article class="advisor-panel" id="advisor-${a.id}" aria-labelledby="name-${a.id}" tabindex="-1"><header class="advisor-heading">${img(a,62)}<div><p>THE ${esc(a.english.toUpperCase())} PERSPECTIVE</p><h3 id="name-${a.id}">${esc(a.name)}<span>分析视角</span></h3><small>${esc(a.focus)}</small></div></header><div class="advisor-questions">${a.questions.map((q,i)=>`<details name="questions-${a.id}"${i===0?' open':''}><summary><span>${String(i+1).padStart(2,'0')}</span><strong>${esc(q.question)}</strong><b aria-hidden="true">＋</b></summary><div class="advisor-answer"><p>${esc(q.answer)}</p><a class="method-link" href="/product-advisory-council/cards/${q.method.toLowerCase()}/">方法线索 · ${esc(q.method)} ${esc(q.methodTitle)} ↗</a></div></details>`).join('')}</div><p class="advisor-footnote">示例展示思考方式；实际分析会结合你的用户、数据与约束。</p></article>`).join('')}</div></div></section>
<section class="council-how" aria-labelledby="how-heading"><div class="council-section-head"><div><span class="council-kicker">02 / FROM PERSPECTIVE TO ACTION</span><h2 id="how-heading">把讨论，带回你的真实问题。</h2></div><p>单人分析，也可以组一场顾问团讨论。</p></div><div class="council-steps"><article><span>01 — 带上问题</span><h3>先说清楚处境</h3><p>谁是用户、现在怎么做、有哪些事实，以及你的资源和期限。未知可以保留未知。</p></article><article><span>02 — 让观点交锋</span><h3>选视角，也保留分歧</h3><p>指定一位顾问，或按问题组织顾问团。比较前提、替代方案和反例，不靠票数决定。</p></article><article><span>03 — 得到下一步</span><h3>从建议走到验证</h3><p>形成条件化建议和最小实验，也能生成群聊网页，把讨论导出为图片或 PDF。</p></article></div></section>
<section class="council-install" id="install" aria-labelledby="install-heading"><div><p class="council-kicker">03 / TAKE IT WITH YOU</p><h2 id="install-heading">下一场讨论，<br>从你的问题开始。</h2><p>下载完整技能包，导入支持 Skills 的 AI 客户端。<br>14 个视角，一次安装；按需参与，不必全员出场。</p><div class="council-actions"><a class="council-primary" href="${repo}/releases/latest" target="_blank" rel="noreferrer">下载 Skill <span>↗</span></a><a href="${repo}#安装一次即可" target="_blank" rel="noreferrer">安装说明 ↗</a></div><small>保留完整 product-advisory-council 文件夹。技能包不附带模型或 API 密钥。</small></div><div class="council-prompt"><div><span>试着这样问</span><button id="copy-prompt" type="button" hidden>复制提问 ↗</button></div><p id="example-prompt">请产品顾问团用中档讨论：我想做一个 AI 笔记工具，但已有很多竞品。先帮我找最关键的差异化假设，再设计一个两周内能做的实验。</p><p class="prompt-tip">安装后，将这段话发给你的 AI 助手。</p><span id="copy-status" role="status" aria-live="polite"></span></div></section>
<p class="council-colophon">独立作品 / LUFFY LIU · 示例依据公开包 v${council.version} · 方法卡用于启发决策，不替代业务事实核查。<a href="${repo}/tree/${council.sourceCommit}" target="_blank" rel="noreferrer">查看内容版本 ↗</a></p></main>${footer}<script type="module" src="/assets/js/council.js"></script></body></html>\n`;
}
