export const videoVersion='0.4.4';
export const videoRepo='https://github.com/CarGod/luffy-video-download-helper';
export const videoDownload=`${videoRepo}/releases/download/v${videoVersion}/Luffy-Video-Download-Helper-${videoVersion}.zip`;
export const videoPath=locale=>locale==='zh-CN'?'/luffy-video-download-helper/':'/en/luffy-video-download-helper/';
export const videoAlternates={'zh-CN':'https://luffyliu.com/luffy-video-download-helper/',en:'https://luffyliu.com/en/luffy-video-download-helper/'};
const home={
 'zh-CN':['Luffy 视频下载','在网页里发现、预览和下载视频，也能让本地 Agent 通过 MCP 调用。开源、无账号，下载压缩包后手动安装。','安装与使用','查看源码'],
 'zh-TW':['Luffy 影片下載','在網頁中發現、預覽與下載影片，也能讓本機 Agent 透過 MCP 呼叫。開源、無帳號，下載壓縮檔後手動安裝。','安裝與使用','查看原始碼'],
 en:['Luffy Video Downloader','Discover, preview and download videos, or use a local Agent through MCP. Open source, no account; install manually from a ZIP.','Install & use','Source code'],
 ja:['Luffy 動画ダウンローダー','ページの動画を検出・プレビュー・保存。ローカル Agent から MCP でも利用できます。アカウント不要、ZIP から手動インストール。','インストール方法','ソースコード'],
 ko:['Luffy 동영상 다운로더','웹페이지 동영상을 찾고 미리 보고 저장하세요. 로컬 Agent에서 MCP로도 사용할 수 있습니다. 계정 없이 ZIP으로 수동 설치합니다.','설치 및 사용','소스 코드'],
 es:['Luffy Video Downloader','Encuentra, previsualiza y descarga vídeos, también desde un Agent local mediante MCP. Código abierto, sin cuenta; instalación manual desde ZIP.','Instalar y usar','Código fuente']
};
export function videoHomeCard(locale='zh-CN'){
 const [name,description,cta,source]=home[locale];const url=videoPath(['zh-CN','zh-TW'].includes(locale)?'zh-CN':'en');
 return `<article class="work-row video-home"><div class="work-row-number" aria-hidden="true">03</div><div class="work-row-copy"><div class="product-lockup"><img src="/assets/video/icon.png" width="58" height="58" alt=""><div><h3>${name}</h3><p>Chrome / Edge · MCP</p></div></div><p>${description}</p><div class="work-meta"><span>MP4 / HLS</span><span>YouTube / X</span><span>MCP</span></div><div class="project-links"><a href="${url}">${cta} ↗</a><a href="${videoRepo}" target="_blank" rel="noreferrer">${source} ↗</a></div></div><a class="work-row-visual" href="${url}" aria-label="${cta}"><img src="/assets/video/videos.png" width="440" height="634" loading="lazy" alt="${name}"><span class="work-product-caption"><strong>${name}</strong><small>DISCOVER · DOWNLOAD · MCP</small></span></a></article>`;
}
export const videoCopy={
 'zh-CN':{
 title:'Luffy 视频下载插件：下载与手动安装教程',description:'Luffy 开源视频下载插件，支持 Chrome / Edge、MP4、HLS 和本地 MCP。下载压缩包，按图文步骤手动安装，接入本地 Agent。',all:'全部项目',name:'Luffy 视频下载',hero:'看到的视频，<br>留在自己手里。',lede:'发现、预览、下载。打开网页就能用，也可以交给本地 Agent。无需账号，视频在本机处理。',download:'下载插件 ZIP',guide:'查看安装教程',source:'GitHub 源码',distribution:'手动安装 · 当前未在扩展商店上架',platform:'Chrome / Edge；YouTube、X 与 MCP 的本机助手目前仅支持 macOS。',shot:'实际插件界面 · 合成视频演示',features:[['网页视频','直链、HLS 分段视频，在列表里预览并选择下载。'],['本机处理','浏览器内合并 HLS；YouTube / X 可交给本机助手解析。'],['Agent 也能用','通过 MCP 查看当前页面、下载视频和查询保存路径。']],install:'从压缩包安装',installIntro:'不需要自己编译。按下面四步，将插件加载到浏览器。首次安装约需几分钟。',steps:[
 ['下载并解压','点击上方「下载插件 ZIP」，解压 <code>Luffy-Video-Download-Helper-0.4.4.zip</code>。里面有 <code>extension/</code>、<code>native/</code> 和安装说明。不要选择 GitHub 自动生成的 Source code 压缩包，它需要自行构建。'],
 ['打开扩展管理页','在 Chrome 地址栏粘贴 <code>chrome://extensions</code>；Edge 使用 <code>edge://extensions</code>。打开页面上的「开发者模式」。'],
 ['加载 extension 文件夹','点击「加载已解压的扩展程序」，选择解压目录里的 <strong>extension</strong> 文件夹，不是 ZIP，也不是最外层文件夹。把这个目录保留在固定位置，浏览器之后仍会读取它。'],
 ['固定插件，播放视频','在工具栏扩展菜单中固定 Luffy。打开目标网页并播放视频，再点击 Luffy。默认显示「发现视频」；没有结果时点击「重新扫描」或刷新原网页再播放。']
 ],tree:'解压后选择这一层',helper:'YouTube / X / MCP：安装本机助手',helperIntro:'只下载普通直链或浏览器内 HLS 时，可跳过这一步。本机助手安装器目前支持 macOS，需要 Python 3.10+、Node.js、FFmpeg。',helperSteps:'如果尚未安装依赖，可先用 Homebrew 运行下面的命令。然后在解压后的目录双击 <code>Install-Luffy-Helper.command</code>，等待「安装完成」。也可在终端进入该目录运行 <code>python3 native/install.py</code>。首次安装需要联网。',helperAfter:'安装后刷新扩展；更新旧助手后如仍提示「未知操作」或版本过旧，请重启浏览器。普通浏览器下载遵循浏览器保存设置；本机下载默认保存在 <code>~/Downloads/Luffy/</code>。',mcp:'让本地 Agent 来下载',mcpSteps:['打开「MCP 服务」Tab，点击「开启服务」。','点击「复制安装说明，发给 Agent」，把完整说明粘贴给你的本地 Agent。','手动配置时，直接查看下方 JSON 框并点击「复制 JSON」。按客户端提示重新连接。','让 Agent 先列出当前页面的视频，指定一个下载，再查询任务直到完成。'],mcpStatus:'绿色：正常运行 · 灰色：未开启 · 红色：异常。服务默认关闭，开关会记住选择。',mcpSample:'“用 Luffy 查看当前页面的视频，下载我选中的那个，完成后告诉我保存路径。”',faq:'使用前，了解这些',faqs:[['更新时怎么做？','下载新版并解压到固定目录，再在扩展管理页刷新插件。如果更换了路径，移除旧扩展后重新加载新目录；新路径安装可能重置扩展设置。助手有更新时重新运行安装器。'],['为什么不能直接从商店安装？','当前采用 GitHub 压缩包分发，尚未提供商店安装入口。这里提供的是手动安装方式，不代表已经收到商店拒绝。'],['所有视频都能下载吗？','不支持 DRM、SAMPLE-AES 和直播。浏览器 HLS 输入上限为 256 MiB；大文件可尝试本机助手。DASH 已有本机入口但未专项验收。源站登录、地区和签名限制仍可能影响下载。'],['会读取浏览器登录状态吗？','默认不读取 Cookie。仅在下载设置里明确选择登录来源后，yt-dlp 才在本机读取相应浏览器 Cookie。'],['关闭弹窗或 MCP，下载会停止吗？','关闭弹窗不影响下载。关闭 MCP 会停止新的 Agent 调用，已开始的任务继续运行；任务记录保留至浏览器会话结束。']]
 },
 en:{
 title:'Luffy Video Downloader — ZIP & Installation Guide',description:'Open-source video downloader for Chrome and Edge with MP4, HLS and local MCP support. Download the ZIP and follow the manual installation guide.',all:'All projects',name:'Luffy Video Downloader',hero:'Keep the video.<br>Keep control.',lede:'Discover, preview, download. Use it from your browser or a local Agent. No account. Media processing stays on your computer.',download:'Download extension ZIP',guide:'Installation guide',source:'Source on GitHub',distribution:'Manual installation · Not currently listed in an extension store',platform:'Chrome / Edge. The helper for YouTube, X and MCP currently supports macOS only.',shot:'Actual extension UI · Synthetic demonstration video',features:[['Videos on the page','Preview direct files and HLS streams, then choose a download.'],['Local processing','Merge HLS in the browser; resolve YouTube / X with the native helper.'],['Ready for Agents','Use MCP to inspect the current page, download a video and find the saved file.']],install:'Install from a ZIP',installIntro:'No build tools needed for the extension ZIP. Follow these four steps to load it into your browser.',steps:[
 ['Download and extract','Use the ZIP button above and extract <code>Luffy-Video-Download-Helper-0.4.4.zip</code>. It contains <code>extension/</code>, <code>native/</code> and instructions. GitHub’s automatic Source code archives require a separate build.'],
 ['Open extension settings','Paste <code>chrome://extensions</code> into Chrome’s address bar, or <code>edge://extensions</code> in Edge. Enable <strong>Developer mode</strong>.'],
 ['Load the extension folder','Click <strong>Load unpacked</strong> and select the <strong>extension</strong> folder inside the extracted directory, not the ZIP or its outer folder. Keep it in a permanent location: the browser continues to read it.'],
 ['Pin Luffy and play a video','Pin Luffy in the toolbar’s extensions menu. Play a video on the target page and open Luffy. The video list appears first; rescan or reload and play again if it is empty.']
 ],tree:'Select this folder after extracting',helper:'YouTube / X / MCP: add the native helper',helperIntro:'Skip this step for ordinary direct downloads or browser HLS. The helper installer currently supports macOS and requires Python 3.10+, Node.js and FFmpeg.',helperSteps:'If needed, install prerequisites with Homebrew using the command below. Then double-click <code>Install-Luffy-Helper.command</code> in the extracted directory and wait for completion. Alternatively, run <code>python3 native/install.py</code> from that directory in Terminal. Initial setup requires internet access.',helperAfter:'Reload the extension after installation. Restart the browser if an updated helper still reports an unknown operation or outdated version. Browser downloads follow browser settings; native output goes to <code>~/Downloads/Luffy/</code>.',mcp:'Let your local Agent download it',mcpSteps:['Open the MCP 服务 tab and enable the service.','Choose 复制安装说明，发给 Agent and send the copied setup instructions to your local Agent.','For manual setup, use the visible JSON box and 复制 JSON. Reconnect as instructed by your client.','Ask your Agent to list the current page’s videos, download your selection, and check the job until complete.'],mcpStatus:'Green: running · Gray: off · Red: error. The service starts disabled and remembers your choice.',mcpSample:'“Use Luffy to list videos on the current page, download the one I choose, and tell me where it was saved.”',faq:'Good to know',faqs:[['How do updates work?','Download the new ZIP, extract to a permanent location and reload the extension. If the path changes, remove the old extension and load the new folder; settings may reset. Re-run the helper installer when it is updated.'],['Why no store install button?','The current distribution method is a GitHub ZIP. There is no store installation entry yet; this does not mean a store rejection has been confirmed.'],['Can it download every video?','DRM, SAMPLE-AES and live streams are unsupported. Browser HLS input is capped at 256 MiB; try the native helper for larger files. DASH has a native route but no dedicated acceptance test. Login, region and expiring URLs may affect downloads.'],['Does it read browser cookies?','Not by default. Local yt-dlp reads browser cookies only after you explicitly select a login source in download settings.'],['Will closing the popup or MCP stop a download?','Closing the popup leaves downloads running. Disabling MCP blocks new Agent calls while existing jobs continue. Job records last for the browser session.']]
 }
};
export function renderVideo({locale,head,header,footer}){
 const t=videoCopy[locale];
 return `<!doctype html><html lang="${locale}"><head>${head}<meta name="theme-color" content="#f7f5ef"><link rel="stylesheet" href="/assets/css/video.css"></head><body>${header}<main id="main" class="video-shell" data-pagefind-body><nav class="video-crumb"><a href="${locale==='en'?'/en/':'/'}#work">${t.all} ↗</a><span>/ ${t.name}</span></nav>
<section class="video-hero"><div><p class="video-kicker"><img src="/assets/video/icon.png" width="28" height="28" alt=""> LUFFY / VIDEO <span>v${videoVersion}</span></p><h1>${t.hero}</h1><p class="video-lede">${t.lede}</p><div class="video-actions"><a class="video-primary" href="${videoDownload}">${t.download} ↓</a><a href="#install">${t.guide} ↘</a></div><p class="video-distribution">${t.distribution}</p><p class="video-platform">${t.platform}</p><a class="video-source" href="${videoRepo}" target="_blank" rel="noreferrer">${t.source} ↗</a></div><figure class="video-shot"><img src="/assets/video/videos.png" width="440" height="634" alt="${t.shot}"><figcaption>${t.shot}</figcaption></figure></section>
<section class="video-features">${t.features.map(([h,p],i)=>`<div><span>0${i+1}</span><h2>${h}</h2><p>${p}</p></div>`).join('')}</section>
<section id="install" class="video-install"><div class="video-section-title"><p class="video-kicker">01 / INSTALL</p><h2>${t.install}</h2><p>${t.installIntro}</p></div><div class="video-steps">${t.steps.map(([h,p],i)=>`<article><span class="video-step-number">0${i+1}</span><div><h3>${h}</h3><p>${p}</p></div></article>`).join('')}</div><div class="video-tree"><p>${t.tree}</p><pre>Luffy-Video-Download-Helper-${videoVersion}/
├── <strong>extension/ ← ${locale==='en'?'Load unpacked':'加载已解压的扩展程序'}</strong>
├── native/
├── Install-Luffy-Helper.command
└── README.md</pre></div></section>
<section id="helper" class="video-helper"><p class="video-kicker">02 / LOCAL HELPER</p><h2>${t.helper}</h2><p>${t.helperIntro}</p><p>${t.helperSteps}</p><pre><code>brew install python node ffmpeg</code></pre><p>${t.helperAfter}</p></section>
<section id="mcp" class="video-mcp"><div><p class="video-kicker">03 / AGENT ACCESS</p><h2>${t.mcp}</h2><ol>${t.mcpSteps.map(x=>`<li>${x}</li>`).join('')}</ol><p class="video-platform">${t.mcpStatus}</p><blockquote>${t.mcpSample}</blockquote></div><figure class="video-shot"><img src="/assets/video/mcp.png" width="440" height="762" loading="lazy" alt="MCP · JSON"><figcaption>${locale==='en'?'Illustrative status and example path; Chinese UI.':'状态和路径为演示配置；当前插件界面为中文。'}</figcaption></figure></section>
<section class="video-faq"><p class="video-kicker">04 / FAQ</p><h2>${t.faq}</h2>${t.faqs.map(([h,p])=>`<details><summary>${h}</summary><p>${p}</p></details>`).join('')}</section>
<div class="video-bottom"><a class="video-primary" href="${videoDownload}">${t.download} ↓</a><a href="${videoRepo}/releases/tag/v${videoVersion}" target="_blank" rel="noreferrer">v${videoVersion} · GitHub Release ↗</a></div></main>${footer}</body></html>`;
}
